project_id = "lnipztrmhtakrmpxvgri"

[functions.ai-chat]
verify_jwt = false

[functions.fetch-leaders]
verify_jwt = true

[functions.fetch-local-news]
verify_jwt = true

[functions.generate-area-report]
verify_jwt = true

[functions.update-leader-photos]
verify_jwt = false
