project_id = "lnipztrmhtakrmpxvgri"

[functions.ai-chat]
verify_jwt = false

[functions.fetch-leaders]
verify_jwt = true

[functions.generate-area-data]
verify_jwt = true

[functions.search-leader]
verify_jwt = false

[functions.populate-famous-leaders]
verify_jwt = false
